name: Update Minor Version
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        token: ${{secrets.PAT}} # use a personal acces token so that other actions can trigger
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x' # You might need to adjust this value to your own version
    - name: Update Minor version
      id: version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm version minor
        echo "::set-output name=tag::$(git describe --abbrev=0)"
    # update the manifest.json with the tag version
    - name: Update manifest version
      uses: jossef/action-set-json-field@v1
      with:
        file: manifest.json
        field: version
        value: ${{ steps.version.outputs.tag }}
    - name: Commit manifest
      run: |
        git add -u
        echo added
        git commit --amend --no-edit
        echo committed
        git tag -fa ${{ steps.version.outputs.tag }} -F
        echo tagged
    # push the commit
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{secrets.PAT}}
        tags: true