name: Bump Version
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of version (`major`, `minor`, `patch`)'
        required: true
        default: 'patch'
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        token: ${{secrets.PAT}} # use a personal acces token so that other actions can trigger
    # Bump the version
    - id: next_version
      uses: zwaldowski/semver-release-action@v1
      with:
        dry_run: true
        bump: ${{ github.event.inputs.type }}
        github_token: ${{ secrets.PAT }}
    - run: echo "${{ steps.next_version.outputs.version }}"
    # update the manifest.json with the tag version
    - name: Update manifest version
      uses: jossef/action-set-json-field@v1
      with:
        file: manifest.json
        field: version
        value: ${{ steps.next_version.outputs.version }}
    - name: Commit manifest
      run: |
        git branch --show-current
        git add -u
        git commit --amend --no-edit
        echo ::set-output name=sha::$(git rev-parse HEAD)
    # push the new tag
    - uses: zwaldowski/semver-release-action@v1
      with:
        github_token: ${{ secrets.PAT }}
        sha: ${{ steps.git_commit.outputs.sha }}
